version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db-metabase:
    image: postgres:16
    container_name: db-metabase
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
      POSTGRES_DB: metabase
    ports:
      - "5432:5432"
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "metabase_user", "-d", "metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-dw:
    image: postgres:16
    container_name: db-dw
    environment:
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
      POSTGRES_DB: dw
    ports:
      - "5433:5432"
    volumes:
      - dw_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dw_user", "-d", "dw"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: api
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  ingestion:
    build: ./ingestion
    container_name: ingestion
    depends_on:
      - redis
      - db-dw
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: db-dw
      PG_PORT: 5432
      PG_DB: dw
      PG_USER: dw_user
      PG_PASSWORD: dw_password
    volumes:
      - ./ingestion:/app

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: db-metabase
    depends_on:
      - db-metabase
    volumes:
      - metabase_data:/metabase-data

volumes:
  redis_data:
  metabase_db_data:
  dw_data:
  metabase_data: 